name: CI

on: [pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Install
        run: pnpm install
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test
      - name: Build (TypeScript 4.x)
        run: pnpm build
      - name: Build (TypeScript 3.x)
        run: |
          pnpm build
